#!/bin/sh
ALBATROSS_USER=albatross

if ! getent group "$ALBATROSS_USER" >/dev/null; then
	groupadd -g 496 $ALBATROSS_USER
fi
if ! getent passwd "$ALBATROSS_USER" >/dev/null; then
	useradd -g 496 -u 496 -d /nonexistent -s /usr/sbin/nologin $ALBATROSS_USER
fi
mkdir -m 0700 -p /var/lib/albatross/block
chown $ALBATROSS_USER:$ALBATROSS_USER /var/lib/albatross /var/lib/albatross/block
