#!/bin/sh

# $FreeBSD$
#
# PROVIDE: albatross_console
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Define these albatross_console_* variables in one of these files
# 	 /etc/rc.conf
#	 /etc/rc.conf.local
#	 /etc/rc.conf.d/albatross_console
#	 /usr/local/etc/rc.conf.d/albatross_console
#
# albatross_console_flags:
#                       Default: ""
#

. /etc/rc.subr

name=albatross_console
rcvar=${name}_enable
desc="Albatross console service"
load_rc_config $name
start_cmd="albatross_console_start"

: ${albatross_console_enable:="NO"}
: ${albatross_console_flags:=""}
: ${albatross_console_user:="albatross"}

pidfile="/var/run/albatross_console.pid"
procname="/usr/local/libexec/albatross/albatross-console"

albatross_console_start () {
    echo "Starting ${name}."
    /usr/sbin/daemon -S -r -P "${pidfile}" -u "${albatross_console_user}" \
		     "${procname}" ${albatross_console_flags}
}

run_rc_command "$1"
