#!/bin/sh

# $FreeBSD$
#
# PROVIDE: albatross_stats
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Define these albatross_stats_* variables in one of these files
# 	 /etc/rc.conf
#	 /etc/rc.conf.local
#	 /etc/rc.conf.d/albatross_stats
#	 /usr/local/etc/rc.conf.d/albatross_stats
#
# albatross_stats_flags:
#                       Default: ""
#

. /etc/rc.subr

name=albatross_stats
rcvar=${name}_enable
desc="Albatross stats service"
load_rc_config $name
start_cmd="albatross_stats_start"

: ${albatross_stats_enable:="NO"}
: ${albatross_stats_flags:=""}
: ${albatross_stats_user:="albatross"}

pidfile="/var/run/albatross_stats.pid"
procname="/usr/local/libexec/albatross/albatross-stats"

albatross_stats_start () {
    echo "Starting ${name}."
    /usr/sbin/daemon -S -p "${pidfile}" -u "${albatross_stats_user}" \
		     "${procname}" ${albatross_stats_flags}
}

run_rc_command "$1"
