#!/bin/sh

# $FreeBSD$
#
# PROVIDE: albatross_log
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Define these albatross_log_* variables in one of these files
# 	 /etc/rc.conf
#	 /etc/rc.conf.local
#	 /etc/rc.conf.d/albatross_log
#	 /usr/local/etc/rc.conf.d/albatross_log
#
# albatross_log_flags:
#                       Default: ""
#

. /etc/rc.subr

name=albatross_log
rcvar=${name}_enable
desc="Albatross log service"
load_rc_config $name
start_cmd="albatross_log_start"
start_precmd="albatross_log_precmd"

: ${albatross_log_enable:="NO"}
: ${albatross_log_flags:=""}
: ${albatross_log_user:="albatross"}

pidfile="/var/run/albatross_log.pid"
procname="/usr/local/libexec/albatross/albatross_log"
logfile="/var/log/albatross"

albatross_log_precmd () {
    [ -e "${logfile}" ] ||
	install -g ${albatross_log_user} -o ${albatross_log_user} \
		-- /dev/null "${logfile}";
}

albatross_log_start () {
    echo "Starting ${name}."
    /usr/sbin/daemon -S -p "${pidfile}" -u "${albatross_log_user}" \
		     "${procname}" ${albatross_log_flags}
}

run_rc_command "$1"
